version: "3.9"

x-protect_crash: &protect_mem_crash_resilient
  restart: unless-stopped # make it crash resilient
  mem_limit: 150m # ram_limit

services:
  bioptim_gui:
    container_name: bioptim_gui
    build:
      context: gui
    image: bioptim_gui:1.0
    networks:
      - internal 
    << : *protect_mem_crash_resilient
    depends_on:
      - bioptim_gui_api

  bioptim_gui_api:
    container_name: bioptim_gui_api
    build:
      context: api 
    image: bioptim_gui_api:1.0 
    networks:
      - internal
    << : *protect_mem_crash_resilient
    ports:
      - "127.0.0.1:8000:8000"

networks:
  internal:
